apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
spec:
  selector:
    matchLabels:
      app: router
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 5
  replicas: {{ .Values.router.replicas }}
  template:
    metadata:
      labels:
        app: router
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: router
        image: "{{ .Values.router.image }}:{{ .Values.router.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 0m
        volumeMounts:
        ports:
        - name: http
          containerPort: 9888
          protocol: TCP
