version: "2"

services:
  reverse-proxy:
    container_name: proxy

    # The official v2 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    # command: --configFile=/home/ec2-user/sphinx-deploy/traefik.yaml
    command:
      - "--log.level=DEBUG"
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
      # entrypoints
      - 443:443
      - 8883:8883
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik.yaml:/etc/traefik/traefik.yaml
      - ./docker/letsencrypt:/letsencrypt
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION

      - CLOUDFLARE_EMAIL=$CLOUDFLARE_EMAIL
      - CLOUDFLARE_API_KEY=$CLOUDFLARE_API_KEY
      - CLOUDFLARE_DNS_API_TOKEN=$CLOUDFLARE_DNS_API_TOKEN
      - CLOUDFLARE_ZONE_API_TOKEN=$CLOUDFLARE_ZONE_API_TOKEN

      - CF_API_EMAIL=$CF_API_EMAIL
      - CF_API_KEY=$CF_API_KEY
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
      - CF_ZONE_API_TOKEN=$CF_ZONE_API_TOKEN

    logging:
      options:
        max-size: 10m
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  # auth:
  #   image: sphinx-auth
  #   depends_on:
  #     - reverse-proxy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.auth.rule=Host(`auth.sphinx.chat`)"
  #     - "traefik.http.services.auth.loadbalancer.server.port=9090"
  #     - "traefik.http.routers.auth.tls=true"
  #     - "traefik.http.routers.auth.tls.certresolver=myresolver"
  #     - "traefik.http.routers.auth.entrypoints=websecure"
  #   restart: on-failure
  #   environment:
  #     - JWT_KEY=$JWT_KEY
  #     - CLIENT_KEYS=$CLIENT_KEYS
  #     - OAUTH_TIMEOUT=$OAUTH_TIMEOUT

  communities:
    container_name: communities
    # image: zion-communities
    build: .
    logging:
      options:
        max-size: "10m"
        max-file: "3"

    depends_on:
      # - auth
      - reverse-proxy
    labels:
      - "traefik.enable=true"

      # # web : insecure
      # - "traefik.http.routers.communities.rule=Host(`communities.getzion.com`)"
      # - "traefik.http.services.communities.loadbalancer.server.port=$PORT"
      # - "traefik.http.routers.communities.entrypoints=web"

      # web : secure
      - "traefik.http.routers.communities.rule=Host(`$TRIBES_HOST`)"
      - "traefik.http.services.communities.loadbalancer.server.port=$PORT"
      - "traefik.http.routers.communities.tls=true"
      - "traefik.http.routers.communities.tls.certresolver=myresolver"
      - "traefik.http.routers.communities.entrypoints=websecure"

      # mqtt : in secure
      - "traefik.tcp.routers.communities.rule=HostSNI(`$TRIBES_HOST`)"
      # - "traefik.tcp.routers.communities.rule=HostSNI(`*`)"
      - "traefik.tcp.services.communities.loadbalancer.server.port=1883"
      - "traefik.tcp.routers.communities.tls=true"
      # - "traefik.tcp.routers.communities.tls=false"
      - "traefik.tcp.routers.communities.tls.certresolver=myresolver"
      - "traefik.tcp.routers.communities.entrypoints=mqttsecure"
      - "traefik.tcp.routers.communities.service=communities"
    restart: on-failure
    environment:
      - TRIBES_HOST=$TRIBES_HOST
      - PORT=$PORT
      - RDS_HOSTNAME=$RDS_HOSTNAME
      - RDS_PORT=$RDS_PORT
      - RDS_DB_NAME=$RDS_DB_NAME
      - RDS_USERNAME=$RDS_USERNAME
      - RDS_PASSWORD=$RDS_PASSWORD
      - JWT_KEY=$JWT_KEY

      - PRIV_KEY=$PRIV_KEY

      - PODCAST_INDEX_KEY=$PODCAST_INDEX_KEY
      - PODCAST_INDEX_SECRET=$PODCAST_INDEX_SECRET
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
