additionalArguments:
  - "--log.level=DEBUG"
  - "--entrypoints.websecure.http.tls"
  - "--entrypoints.mqttsecure.http.tls"
  # - "--entryPoints.websecure.address=:443"
  # - "--entryPoints.web.address=:80"
  - "--providers.kubernetesIngress.ingressClass=traefik-cert-manager"
  - "--ping"
  - "--metrics.prometheus"

ports:
  web:
    port: 80
    expose: true
    exposedPort: 80
    protocol: TCP
  mqttsecure:
    port: 8883
    expose: true
    exposedPort: 8883
    protocol: TCP
  websecure:
    port: 443
    expose: true
    exposedPort: 443
    protocol: TCP

# logs:
#   general:
#     level: DEBUG # DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.



securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

podSecurityContext:
  fsGroup: 65532
