apiVersion: apps/v1
kind: Deployment
metadata:
  name: communities
spec:
  selector:
    matchLabels:
      app: communities
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 5
  replicas: {{ .Values.communities.replicas }}
  template:
    metadata:
      labels:
        app: communities
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: communities
        image: "{{ .Values.communities.image }}:{{ .Values.communities.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 0m
        volumeMounts:
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        - name: mqtts
          containerPort: 8883
          protocol: TCP
        - name: cluster
          containerPort: 1993
          protocol: TCP
        envFrom:
        - secretRef:
            name: communities
