apiVersion: v1
kind: Service
metadata:
  name: communities
spec:
  selector:
    app: communities
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqtts
      protocol: TCP
      port: 8883
      targetPort: 8883
    - name: web
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: cluster
      protocol: TCP
      port: 1993
      targetPort: 1993
